### ISSUE TITLE
typo in line 955 of swagger.py

### ISSUE THREAD

**Issue by jovonmcc** [Arello-Mobile/swagger2rst#3]
line 955 in swagger.py:    self.name += '_array'  
causes "TypeError: unsupported operand type(s) for +=: 'int' and 'str' "  

should be self.name = '_array'

**Comment by i-koverdyaev** [comment]
Hello,
It seems that you have a property of type "array" with a numerical name. Like:
```json
...
"FooSerializer": {
    "type": "object",
    "properties": {
        123: {
            "type": "array",
            "items": {
                "$ref": "#/definitions/BarSerializer"
            }
        }
    }
}
...
```
Please ensure that the name is wrapped in double quotes. After the closing of #4  , the error message will be more informative.
