### ISSUE TITLE
keep order of definitions from spec file

### ISSUE THREAD

**Issue by ghost** [Arello-Mobile/swagger2rst#5]
thank you for the swagger2rst tool... very helpful

* I read in the spec from yaml into an OrderedDict
* in the `definition.rst` template I use `doc.schemas.get_schemas(['definition'], sort=False)...`
* still get weird order of definitions in the rst output

I could identify where in the code it scrambles the definitions `schema_objects.py`:

line 1
```
from collections import OrderedDict
```

line 12
```
    _schemas = OrderedDict()
```

and line 81:
```
    cls._schemas = OrderedDict()
```
any chance to get this in soon? I do not like to maintain a fork :)

**Comment by irr123** [comment]
@markfink apply your suggestion f1d81453cbcc21f2f3c49f5b65e67f3664e01f6b
